# https://docs.docker.com/engine/install/debian/

- name: Uninstall old Docker versions
  package:
    state: absent
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc


- name: Set up repository
  package:
    state: latest
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release


- name: Add Dockerâ€™s official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/trusted.gpg.d/docker-keyring.gpg


- name: Add repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker-keyring.gpg] https://download.docker.com/linux/debian bookworm stable
    state: present
    filename: docker


- name: apt update
  apt:
    update_cache: yes


- name: Install Docker Engine
  package:
    state: latest
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin


- name: Add the {{ sudo_user }} user to the 'docker' group
  user: name={{ sudo_user }} groups=docker append=yes
  when: sudo_user is defined and sudo_user != None


#- name: Copy Docker config and notify restart Docker
#  ansible.builtin.template:
#    src=files/daemon.json.j2
#    dest=/etc/docker/daemon.json
#  notify: Restart Docker
