ansible_become: yes
ansible_become_method: sudo
ansible_become_user: root

tuned_profile: virtual-guest
time_zone: Europe/Saratov
sudo_user: zzz
sudo_user_copy_ssh_pub_key: ~/.ssh/id_rsa.pub

locales_to_be_generated:
  - en_GB.UTF-8 UTF-8
  - en_US.UTF-8 UTF-8
  - ru_RU.UTF-8 UTF-8
locale_default: en_GB.UTF-8

docker_iptables: 'false'
zabbix_server: zabbix-server

swap_file_size_mb: 1024 # 0 - disable
swap_file_path: /swapfile
swappiness: 5

bin_dir: /usr/local/bin

deploy_tool_aws_enabled: True

deploy_tool_terragrunt_enabled: True
deploy_tool_terragrunt_version: latest
#deploy_tool_terragrunt_version: v0.38.4

deploy_tool_terraform_enabled: True
deploy_tool_terraform_version: latest
#deploy_tool_terraform_version: 1.1.4
